//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Posetit
    {
        public Posetit()
        {
            this.Zayavky = new HashSet<Zayavky>();
        }
    
        public int Id_pos { get; set; }
        public string FIO { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
        public string Telephone { get; set; }
    
        public virtual ICollection<Zayavky> Zayavky { get; set; }
    }
}
