//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Sotrudnik
    {
        public Sotrudnik()
        {
            this.Zapisi = new HashSet<Zapisi>();
            this.Zayavky = new HashSet<Zayavky>();
        }
    
        public int ID_sotr { get; set; }
        public string Name_sotr { get; set; }
        public string Dolzn { get; set; }
        public string Login { get; set; }
        public string Pass { get; set; }
    
        public virtual ICollection<Zapisi> Zapisi { get; set; }
        public virtual ICollection<Zayavky> Zayavky { get; set; }
    }
}
