//------------------------------------------------------------------------------
// <auto-generated>
//    Этот код был создан из шаблона.
//
//    Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//    Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Exam1
{
    using System;
    using System.Collections.Generic;
    
    public partial class Zapisi
    {
        public int Id_zapis { get; set; }
        public string FIO { get; set; }
        public string Name_usl { get; set; }
        public Nullable<System.DateTime> Data_z { get; set; }
        public Nullable<int> Id_sotr { get; set; }
    
        public virtual Sotrudnik Sotrudnik { get; set; }
    }
}
